spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fintech-company}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always

server:
  port: ${PRODUCT_ENGINE_PORT:8086}

grpc:
  server:
    port: ${PRODUCT_ENGINE_GRPC_PORT:9091}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false

scheduler:
  checkOverdueRate: 86400000
