spring:
  datasource:
    url:
      jdbc:postgresql://db:5432/fintech-company
    username:
      postgres
    driver-class-name:
      org.postgresql.Driver
    password:
      123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log:
      classpath:db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always

server:
  port: 8086

grpc:
  server:
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false
