grpc:
  client:
    grpc-server:
      address: 'static://${ORIGINATION_GRPC_HOST}:${ORIGINATION_GRPC_PORT}'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true