grpc:
  client:
    grpc-server:
      address: 'static://${PRODUCT_ENGINE_GRPC_HOST}:${PRODUCT_ENGINE_GRPC_PORT}'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true