server:
  port: ${SERVER_PORT:8087}

grpc:
  client:
    grpc-server:
      address: static://${GRPC_HOST_PRODUCT_ENGINE:localhost}:${GRPC_PORT_PRODUCT_ENGINE:9091}
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
  server:
    port: ${SERVER_PORT_GRPC:9095}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false

late:
  payment:
    threshold:
      days: ${LATE_PAYMENT_THRESHOLD_DAYS:7}
