spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/origination
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log:
      classpath:db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always
  mail:
    properties:
      mail:
        smtp:
          starttls:
            required: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

mail:
  default-encoding: UTF-8
  host: smtp.gmail.com
  username: businessmyhomeq@gmail.com
  password: ocebvucvtygzckwx
  port: 587
  protocol: smtp

application:
  email:
    subject: "Status application in TinkBank"
    message-template: "Hello, %s. Your application %s has %s status"

server:
  port: 8084

grpc:
  server:
    port: 9094
    enable-reflection: true
  client:
    grpc-server:
      address: ${GRPC_CLIENT_GRPC_SERVER_ADDRESS:localhost:9095}
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false

outbox:
  application:
    pendingTimeoutInSeconds: 10
    retryMaxAttempts: 3
    kafkaTransformTimeout: 60000
    kafkaSendTimeout: 180000
    exporter:
      fixed-rate: 1000
    stalled:
      fixed-rate: 1000

exporter:
  application:
    topic: "v1.origination"
