on:
  pull_request:
    branches:
      - master
      - origination-implement
      - feature/payment-gate-integration
  push:
    branches:
      - master
      - origination-implement
      - feature/payment-gate-integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: "./gradlew bootJar test --no-daemon --no-build-cache"

